version: '3'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=Mark
      - MYSQL_ROOT_PASSWORD=Password123#@!
      - MYSQL_DATABASE=test